# Generated by Django 5.0.1 on 2024-11-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_announcements_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
