export const CREATE_CONTACT_US_REQUEST = 'CREATE_CONTACT_US_REQUEST'
export const CREATE_CONTACT_US_SUCCESS = 'CREATE_CONTACT_US_SUCCESS'
export const CREATE_CONTACT_US_ERROR = 'CREATE_CONTACT_US_ERROR'
export const CREATE_CONTACT_US_RESET = 'CREATE_CONTACT_US_RESET'

