//for geting latest book or chapter
export const GET_LATEST_EVENT_REQUEST = 'GET_LATEST_EVENT_REQUEST'
export const GET_LATEST_EVENT_SUCCESS = 'GET_LATEST_EVENT_SUCCESS'
export const GET_LATEST_EVENT_ERROR = 'GET_LATEST_EVENT_ERROR'
export const GET_LATEST_EVENT_RESET = 'GET_LATEST_EVENT_RESET'


//for listing upcoming book or chapter
export const CREATE_UPCOMING_EVENT_REQUEST = 'CREATE_UPCOMING_EVENT_REQUEST'
export const CREATE_UPCOMING_EVENT_SUCCESS = 'CREATE_UPCOMING_EVENT_SUCCESS'
export const CREATE_UPCOMING_EVENT_ERROR = 'CREATE_UPCOMING_EVENT_ERROR'
export const CREATE_UPCOMING_EVENT_RESET = 'CREATE_UPCOMING_EVENT_RESET'

export const UPDATE_UPCOMING_EVENT_REQUEST = 'UPDATE_UPCOMING_EVENT_REQUEST'
export const UPDATE_UPCOMING_EVENT_SUCCESS = 'UPDATE_UPCOMING_EVENT_SUCCESS'
export const UPDATE_UPCOMING_EVENT_ERROR = 'UPDATE_UPCOMING_EVENT_ERROR'
export const UPDATE_UPCOMING_EVENT_RESET = 'UPDATE_UPCOMING_EVENT_RESET'

export const DELETE_UPCOMING_EVENT_REQUEST = 'DELETE_UPCOMING_EVENT_REQUEST'
export const DELETE_UPCOMING_EVENT_SUCCESS = 'DELETE_UPCOMING_EVENT_SUCCESS'
export const DELETE_UPCOMING_EVENT_ERROR   = 'DELETE_UPCOMING_EVENT_ERROR'
export const DELETE_UPCOMING_EVENT_RESET   = 'DELETE_UPCOMING_EVENT_RESET'

export const GET_UPCOMING_EVENT_REQUEST = 'GET_UPCOMING_EVENT_REQUEST'
export const GET_UPCOMING_EVENT_SUCCESS = 'GET_UPCOMING_EVENT_SUCCESS'
export const GET_UPCOMING_EVENT_ERROR   = 'GET_UPCOMING_EVENT_ERROR'
export const GET_UPCOMING_EVENT_RESET   = 'GET_UPCOMING_EVENT_RESET'


//for posting text upcoming book or chapter news
export const CREATE_ANOUCEMENT_REQUEST = 'CREATE_ANOUCEMENT_REQUEST'
export const CREATE_ANOUCEMENT_SUCCESS = 'CREATE_ANOUCEMENT_SUCCESS'
export const CREATE_ANOUCEMENT_ERROR = 'CREATE_ANOUCEMENT_ERROR'
export const CREATE_ANOUCEMENT_RESET = 'CREATE_ANOUCEMENT_RESET'

export const GET_ANOUCEMENT_REQUEST = 'GET_ANOUCEMENT_REQUEST'
export const GET_ANOUCEMENT_SUCCESS = 'GET_ANOUCEMENT_SUCCESS'
export const GET_ANOUCEMENT_ERROR = 'GET_ANOUCEMENT_ERROR'
export const GET_ANOUCEMENT_RESET = 'GET_ANOUCEMENT_RESET'

export const UPDATE_ANOUCEMENT_REQUEST = 'UPDATE_ANOUCEMENT_REQUEST'
export const UPDATE_ANOUCEMENT_SUCCESS = 'UPDATE_ANOUCEMENT_SUCCESS'
export const UPDATE_ANOUCEMENT_ERROR = 'UPDATE_ANOUCEMENT_ERROR'
export const UPDATE_ANOUCEMENT_RESET = 'UPDATE_ANOUCEMENT_RESET'

export const DELETE_ANOUCEMENT_REQUEST = 'DELETE_ANOUCEMENT_REQUEST'
export const DELETE_ANOUCEMENT_SUCCESS = 'DELETE_ANOUCEMENT_SUCCESS'
export const DELETE_ANOUCEMENT_ERROR = 'DELETE_ANOUCEMENT_ERROR'
export const DELETE_ANOUCEMENT_RESET = 'DELETE_ANOUCEMENT_RESET'