export const CREATE_STORY_REQUEST = 'CREATE_STORY_REQUEST'
export const CREATE_STORY_SUCCESS = 'CREATE_STORY_SUCCESS'
export const CREATE_STORY_ERROR = 'CREATE_STORY_ERROR'

export const CREATE_CHAPTER_REQUEST = 'CREATE_CHAPTER_REQUEST'
export const CREATE_CHAPTER_SUCCESS = 'CREATE_CHAPTER_SUCCESS'
export const CREATE_CHAPTER_ERROR = 'CREATE_CHAPTER_ERROR'
export const CREATE_CHAPTER_RESET = 'CREATE_CHAPTER_RESET'

export const LIST_STORY_REQUEST = 'LIST_STORY_REQUEST'
export const LIST_STORY_SUCCESS = 'LIST_STORY_SUCCESS'
export const LIST_STORY_ERROR = 'LIST_STORY_ERROR'

export const READ_STORY_DETAILS_REQUEST = 'READ_STORY_DETAILS_REQUEST'
export const READ_STORY_DETAILS_SUCCESS = 'READ_STORY_DETAILS_SUCCESS'
export const READ_STORY_DETAILS_ERROR = 'READ_STORY_DETAILS_ERROR'

export const READ_CHAPTER_REQUEST = 'READ_CHAPTER_REQUEST'
export const READ_CHAPTER_SUCCESS = 'READ_CHAPTER_SUCCESS'
export const READ_CHAPTER_ERROR = 'READ_CHAPTER_ERROR'
export const READ_CHAPTER_RESET = 'READ_CHAPTER_RESET'

export const LIST_CHAPTER_REQUEST = 'LIST_CHAPTER_REQUEST'
export const LIST_CHAPTER_SUCCESS = 'LIST_CHAPTER_SUCCESS'
export const LIST_CHAPTER_ERROR = 'LIST_CHAPTER_ERROR'

export const LIST_ADMIN_STORY_REQUEST = 'LIST_ADMIN_STORY_REQUEST'
export const LIST_ADMIN_STORY_SUCCESS = 'LIST_ADMIN_STORY_SUCCESS'
export const LIST_ADMIN_STORY_ERROR = 'LIST_ADMIN_STORY_ERROR'

export const LIST_ADMIN_CHAPTER_REQUEST = 'LIST_ADMIN_CHAPTER_REQUEST'
export const LIST_ADMIN_CHAPTER_SUCCESS = 'LIST_ADMIN_CHAPTER_SUCCESS'
export const LIST_ADMIN_CHAPTER_ERROR   = 'LIST_ADMIN_CHAPTER_ERROR'

export const UPDATE_CHAPTER_REQUEST = 'UPDATE_CHAPTER_REQUEST'
export const UPDATE_CHAPTER_SUCCESS ='UPDATE_CHAPTER_SUCCESS'
export const UPDATE_CHAPTER_ERROR ='UPDATE_CHAPTER_ERROR'
export const UPDATE_CHAPTER_RESET ='UPDATE_CHAPTER_RESET'

export const UPDATE_STORY_REQUEST = 'UPDATE_STORY_REQUEST'
export const UPDATE_STORY_SUCCESS ='UPDATE_STORY_SUCCESS'
export const UPDATE_STORY_ERROR ='UPDATE_STORY_ERROR'
export const UPDATE_STORY_RESET ='UPDATE_STORY_RESET'
